(use-modules (guix)
             (guix build-system haskell)
             (guix licenses)
             (guix packages)
             (gnu packages haskell)
             (nat guix packages haskell))

(package (inherit haskell-project)
  (name "ghc-keywee")
  (version "0.0.1.0")
  (source (local-file "./."))
  (build-system haskell-build-system)
  (inputs
   `(("ghc-aeson" ,ghc-aeson)
     ("ghc-async" ,ghc-async)
     ("ghc-conduit" ,ghc-conduit)
     ("ghc-conduit-combinators" ,ghc-conduit-combinators)
     ("ghc-conduit-extra" ,ghc-conduit-extra)
     ("ghc-mono-traversable" ,ghc-mono-traversable)
     ("ghc-semigroups" ,ghc-semigroups)
     ("ghc-text" ,ghc-text)
     ("ghc-process" ,ghc-process)
     ("ghc-wires" ,ghc-wires)))
  (home-page
    "http://github.com/jkopanski/keywee#readme")
  (synopsis "Keybase chat plugin for WeeChat")
  (description "Please see README.md")
  (license gpl3))
