version: 2
jobs:
  setup:
    docker:
      - image: fpco/stack-build:lts-10.4
    steps:
      - run: stack upgrade
      - checkout
      - restore_cache:
          keys:
            - stack-deps
      - run: stack setup
      - run: stack build --only-dependencies
      - save_cache:
          key: stack-deps
          paths:
            - ~/.stack
            - .stack-work
            - .stack

  build:
    docker:
      - image: fpco/stack-build:lts-10.4
    steps:
      - run: stack build
      - run: stack exec perl opts.pl keywe
      - run: make all

workflows:
  version: 2
  build:
    jobs:
      - setup
      - build:
          requires:
            - setup
